SELECT [ID]
      ,[ShowClassID]
      ,[Place]
      ,[Entry]
      ,[HorseID]
      ,[Country]
      ,[Prize]
      ,[AddBack]
      ,[Start]
      ,[Score]
      ,[Percent]
      ,[USEF]
      ,[EC]
      ,[RiderID]
      ,[TrainerID]
      ,[CreatedDate]
      ,[UpdatedDate]
  FROM [HorseShows].[sResults].[ShowResults]

  --delete [HorseShows].[sResults].[ShowResults]