SELECT [ID]
      ,[Year]
      ,[ShowName]
      ,[StartDate]
      ,[EndDate]
      ,[ShowDate]
      ,[ShowLocation]
      ,[StateProv]
      ,[GoverningBody]
      ,[ShowGUID]
      ,[CreatedDate]
      ,[UpdatedDate]
  FROM [HorseShows].[sResults].[ShowList]

  select * from [HorseShows].[sResults].[ShowList] where showname like '%bridlespur%'